# Generated by Django 2.0.5 on 2018-06-20 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180620_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 14, 32, 8, 533721, tzinfo=utc)),
        ),
    ]
