# Generated by Django 2.0.5 on 2018-06-20 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180620_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 14, 41, 0, 772961, tzinfo=utc)),
        ),
    ]
